version: "3.9"

services:
  frontend:
    restart: always
    container_name: dow-dash
    ports:
      - 3000:3000
    image: ${IMAGE}:${TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
